[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.0"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  version = "1.0.0"

# Gladius Packages
[[constraint]]
  name = "github.com/gladiusio/gladius-utils"
  version = "~0.3.0"
